### GO enrichment

Next, let's look for enrichment in the modules detected using WGCNA.

```{r gene_lengths_network}
# Redefine gene lengths in case DE enrichment was not run
gene_ids <- gene_info$gene_id

# Create gene lengths vector
gene_lengths <- gene_info$transcript_length
names(gene_lengths) <- gene_info$gene_id
```

```{r go_enrichment_modules, message=FALSE, warning=FALSE, results='hide', cache=CONFIG$use_cache, autodep=TRUE, eval=CONFIG$module_enrichment}
# Initiallize parallelization
#cl <- makeCluster(max(1, min(12, detectCores() - 2)))
cl <- makeCluster(2)
registerDoParallel(cl)

message("Performing GO enrichment")

# Check each module for enrichment in GO terms and save result in a list
module_go_enrichment <- foreach(color=unique(module_colors), .packages=c('goseq')) %dopar% {
    # Measure GO enrichment for module
    enriched <- tryCatch({
        # module gene ids
        in_module_geneids <- gene_ids[module_colors == color]

        message(sprintf("[GO enrichment] %s", color))
    
        # for host go enrichment, take advantage of goseq's internal mapping
        if (CONFIG$target == 'host' && CONFIG$host != 'C. elegans') {
            enriched <- test_host_go_enrichment(in_module_geneids, gene_ids,
                                                CONFIG$organism_genome)
        } else {
            # parasite / c. elegans GO enrichment
            enriched <- test_gene_enrichment(in_module_geneids, gene_ids,
                                             gene_go_mapping, gene_lengths)
        }

        # Add descriptions
        #enriched <- merge(enriched, go_term_id_mapping, by='category')
    }, error=function(e) {
        # goseq fails in some cases; have not been able to track down cause yet
        # to avoid errors we will just return an empty result set
        warning(sprintf("GO enrichment failed for module %s", color))
        cbind(
            get_enrichment_placeholder(),
            term=numeric(0),
            ontology=numeric(0)
        )
    })
    enriched
}
names(module_go_enrichment) <- unique(module_colors)

# remove any null/empty entries from the results
module_go_enrichment <- module_go_enrichment[!sapply(module_go_enrichment, is.null)]

# unregister cpus
stopCluster(cl)
```

```{r print_go_enrichment_modules, results='asis', eval=CONFIG$module_enrichment}
# Print enrichment results
tmp <- cbind(gene=gene_ids, color=module_colors)
gene_mapping <- merge(gene_go_mapping, tmp, by='gene')

cat(sprintf('- Total enriched modules: %d\n', 
            sum(sapply(module_go_enrichment, nrow) > 0)))

if (CONFIG$include_tables) {
    print_enrichment_results(module_go_enrichment, module_sizes, 'GO terms',
                             #NULL, gene_mapping, 'output/modules', 
                             NULL, gene_mapping, 
                             enrichment_type='go',
                             include_gene_lists=FALSE)
}

enriched_colors_go <- get_enriched_modules(module_go_enrichment)

# Module enrichment status (used in dendrogram plots)
go_enrichment_status   <- as.numeric(module_colors %in% enriched_colors_go)

# save results
COEXPRESSION_NETWORK_RESULT$enriched_colors_go <- enriched_colors_go
COEXPRESSION_NETWORK_RESULT$module_go_enrichment <- module_go_enrichment
COEXPRESSION_NETWORK_RESULT$go_term_id_mapping <- go_term_id_mapping
```
