### Marbach et al. (2016) TF regulon enrichment

Next, we will look for enrichment of genes regulated by the same TF, as
inferred from Marbach *et al* (2016).

```{r load_marbach_tf_network_data, results='asis', warnings=FALSE}
library('tftargets')

# read_table also works in more recent versions of R...
gene_tf_mapping <- data.frame(category=rep(names(Marbach2016), lapply(Marbach2016, length)),
                              gene=unlist(Marbach2016, recursive=FALSE))

# convert HGNC gene identifiers to ENSEMBL identifiers
gene_id_mapping <- setNames(
    AnnotationDbi::select(orgdb, keys=unique(gene_tf_mapping$gene), keytype='ALIAS', 
                          columns=c('ENSEMBL')), c('gene', 'gid_ensembl')
)

ind <- match(gene_tf_mapping$gene, gene_id_mapping$gene)
gene_tf_mapping$gene <- gene_id_mapping$gid_ensembl[ind]

# drop any entries that could not be mapped
gene_tf_mapping <- gene_tf_mapping[complete.cases(gene_tf_mapping),]

if (CONFIG$verbose && CONFIG$include_tables) {
    cat("\nPreview of gene / TF mapping:\n")
    kable(head(gene_tf_mapping))
}
```

Look for enrichment of co-regulated genes.

```{r marbach_coregulated_gene_enrichment, message=FALSE, warning=FALSE, results='hide', cache=CONFIG$use_cache, autodep=TRUE}
# Initialize CPUs
cl = makeCluster(min(12, detectCores() - 1))
registerDoParallel(cl)

# Check each module for enrichment in co-regulated genes and save result in a list
module_coreg_enrichment = foreach(color=unique(module_colors), .packages=c('goseq')) %dopar% {
    # Measure enrichment for module
    enriched = tryCatch({
        in_module_geneids = gene_ids[module_colors == color]
        enriched = test_gene_enrichment(in_module_geneids, gene_ids,
                                        gene_tf_mapping, gene_lengths)
    }, error=function(e) {
        # goseq fails in some cases; have not been able to track down cause yet
        # Note: goseq will also fail if supplied with a dplyr tbl_df so first 
        # make sure that is not the case
        warning(sprintf("Marbach2016 co-regulation enrichment failed for module %s", color))
        return(get_enrichment_placeholder())
    })
    enriched
}

names(module_coreg_enrichment) = unique(module_colors)

# remove any null entries from the results
module_coreg_enrichment = module_coreg_enrichment[!sapply(module_coreg_enrichment, is.null)]

# unregister cpus
stopCluster(cl)

# module enrichment status
enriched_colors_marbach <- get_enriched_modules(module_coreg_enrichment)
marbach_enrichment_status <- as.numeric(module_colors %in%
                                        enriched_colors_marbach)
```

```{r marbach_enrichment_results, results='asis'}
if (CONFIG$include_tables) {
    print_enrichment_results(module_coreg_enrichment, module_sizes,
                             'Transcription Factor')
}
```

```{r save_hsapiens_annotations}
# sort result
sorted_result = tbl_df(result[with(result, order(color, description)),])

# Also save a simplified version of the table for display in the HTML output
simple_result = sorted_result
```

