### LeishCyc pathway enrichment

source: http://www.biocyc.org/LEISH/organism-summary?object=LEISH

```{r load_leishcyc, results='asis'}
# load data
leishcyc_infile <- file.path(Sys.getenv('DATA'), 'annotations', 'leishcyc', 'LeishCyc_19.5_mapping.csv')

# load full LeishCyc mapping
leishcyc_mapping <- read.csv(leishcyc_infile)
colnames(leishcyc_mapping) <- c('category', 'gene_id')
```

```{r leishcyc_gene_enrichment, message=FALSE, warning=FALSE, results='hide', cache=CONFIG$use_cache, autodep=TRUE}
# Initialize CPUs
cl <- makeCluster(max(1, min(10, detectCores() - 2, na.rm = TRUE)))
registerDoParallel(cl)

# Check each module for pathway enrichment and save result in a list
module_leishcyc_enrichment <- foreach(color=unique(module_colors), .packages=c('goseq')) %dopar% {
  set.seed(1)

  # Measure enrichment for module
  enriched <- tryCatch({
    in_module_geneids <- gene_ids[module_colors == color]
    enriched <- test_gene_enrichment(in_module_geneids, gene_ids, leishcyc_mapping, gene_lengths)
  }, error=function(e) {
    # goseq fails in some cases; have not been able to track down cause yet Note: goseq will also
    # fail if supplied with a dplyr tbl_df so first make sure that is not the case
    warning(sprintf("LeishCyc enrichment failed for module %s", color))
    return(get_enrichment_placeholder())
  })
  enriched
}
names(module_leishcyc_enrichment) <- unique(module_colors)

# remove any null entries from the results
module_leishcyc_enrichment <- module_leishcyc_enrichment[!sapply(module_leishcyc_enrichment, is.null)]

# module enrichment status
enriched_colors_leishcyc <- get_enriched_modules(module_leishcyc_enrichment)
leishcyc_enrichment_status <- as.numeric(module_colors %in%
                                         enriched_colors_leishcyc)

# unregister cpus
stopCluster(cl)
```

```{r leishcyc_enrichment_results, results='asis'}
if (CONFIG$include_tables) {
    cat(sprintf('- Total enriched modules: %d\n', 
                sum(sapply(module_leishcyc_enrichment, nrow) > 0)))

    print_enrichment_results(module_leishcyc_enrichment, module_sizes, 
                             'LeishCyc Pathway', output_dir='output/modules',
                             enrichment_type='leishcyc')
}
```

