Module Statistics
-----------------

Create a dataframe with module-specific statistics.

```{r create_module_stats_df}
# create a list including all enrichment results
module_enrichment_results <- list(
    go=module_go_enrichment,
    kegg=module_kegg_enrichment
)

if ('module_leishcyc_enrichment' %in% ls()) {
    module_enrichment_results[['leishcyc']] <- module_leishcyc_enrichment
}

if ('module_cpdb_enrichment' %in% ls()) {
    module_enrichment_results[['cpdb']] <- module_cpdb_enrichment
}

if ('module_msigdb_enrichment' %in% ls()) {
    module_enrichment_results[['msigdb']] <- module_msigdb_enrichment
}

if ('module_coreg_enrichment' %in% ls()) {
    module_enrichment_results[['marbach']] <- module_coreg_enrichment
}

# temporarily recreate correlation matrix to compute module stats
correlation_matrix <- coop::pcor(t(wgcna_input))
module_stats <- create_module_stats_df(result, correlation_matrix, wgcna_input,
                                       main_contrast, module_enrichment_results)
# free up memory
rm(correlation_matrix)
gc()
```

### Functionally enriched modules

```{r results='asis'}
module_stats %>% 
    select(-mean_expr, -mean_gene_var, -min_correlation, -max_correlation,
           -mean_correlation, -median_correlation, -intra_module_var) %>%
    filter(num_enriched_total > 0) %>%
    xkable
```
