### MSigDB pathway enrichment

```{r load_msigdb, results='asis'}
# MSigDB collections to include
msigdb_collections <- c('h.all', 'c2.cp.reactome', 'c2.cp.biocarta', 'c3.mir', 'c3.tft', 'c6.all')

# load MSigDB gene sets
msigdb_mapping <- NULL

for (collection in msigdb_collections) {
  infile <- file.path(Sys.getenv('DATA'), 'annotations', 'msigdb', 'v6.2', 
                      sprintf('%s.v6.2.entrez.gmt', collection))
  msigdb_mapping <- rbind(msigdb_mapping, parse_gmt(infile, keytype = 'entrez'))
}

# convert entrez -> ensembl ids
msigdb_mapping$gene <- grch37$ensgene[match(msigdb_mapping$gene, grch37$entrez)]

# drop any entries that couldn't be mapped
msigdb_mapping <- msigdb_mapping[!is.na(msigdb_mapping$gene), ]
```

```{r msigdb_gene_enrichment, message=FALSE, warning=FALSE, results='hide', cache=CONFIG$use_cache, autodep=TRUE}
# Initialize CPUs
cl <- makeCluster(max(1, min(10, detectCores() - 2, na.rm = TRUE)))
registerDoParallel(cl)

message("Performing MSigDB enrichment")

# Check each module for pathway enrichment and save result in a list
module_msigdb_enrichment <- foreach(color=unique(module_colors), .packages=c('goseq')) %dopar% {
    # Measure enrichment for module
    enriched <- tryCatch({
        in_module_geneids <- gene_ids[module_colors == color]
        enriched <- test_gene_enrichment(in_module_geneids, gene_ids,
                                         msigdb_mapping, gene_lengths)
    }, error=function(e) {
        # goseq fails in some cases; have not been able to track down cause yet
        # Note: goseq will also fail if supplied with a dplyr tbl_df so first 
        # make sure that is not the case
        warning(sprintf("MSigDB enrichment failed for module %s", color))
        return(get_enrichment_placeholder())
    })
    enriched
}
names(module_msigdb_enrichment) <- unique(module_colors)

# remove any null entries from the results
module_msigdb_enrichment <- module_msigdb_enrichment[!sapply(module_msigdb_enrichment, is.null)]

# unregister cpus
stopCluster(cl)

# module enrichment status
enriched_colors_msigdb <- get_enriched_modules(module_msigdb_enrichment)
msigdb_enrichment_status <- as.numeric(module_colors %in% enriched_colors_msigdb)
```

```{r msigdb_enrichment_results, results='asis'}
cat(sprintf('- Total enriched modules: %d\n', 
            sum(sapply(module_msigdb_enrichment, nrow) > 0)))

if (CONFIG$include_tables) {
    print_enrichment_results(module_msigdb_enrichment, module_sizes,
                                'MSigDB Gene Set',
                                msigdb %>% select(category=external_id, pathway, source))
}
```

